### ISSUE TITLE
Remove ID from schedule table

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#10]
The left most column of the schedule table is schedule item ID. This does not have much meaning for the user. Important for the system, yes, but the ID is not something we can edit, or need to know, or affects function from our perspective. Table would be cleaner and clearer without this column.

**Comment by KipK** [comment]
It's intended, to recognise identical Timers without rolling over the schedule icon, if you already know them.
But I guess as they don't change order, we could remember their position. 
Perhaps if there's a lot of timers this has some sense ? ( I'll have to do a pagin of the list for this case ) 
Best would be to find a way to display the days that would fit on mobile screen

**Comment by fhteagle** [comment]
Hmm. Some ideas. Use one icon that means "this schedule is active every day" , and a different icon(s) for either A) a single one that means "this schedule ID is only active some days" , or B) seven checkboxes for the active days on the schedule table.

Better, though, I think, are the examples that JeremyPoulter gave of how smart thermostats show the schedule graphically, one row per day, left to right being from midnight to midnight showing on/off/heat/cooling /etc.  

See this:
https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/6

Graphical bars showing the schedule is the most slick, if you can pull it off.

**Comment by KipK** [comment]
I've removed the ID for now. Will see later for the calendar range setting. It's tricky to display like this as we can have short timeranges to display.
