### ISSUE TITLE
Settings submenu popup in icon bar

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#15]
Testing the UI on mobile in Vivaldi and Firefox Focus at commit d1bc5425c87fcb308260ce711f3012265b34270e : 

When I short tap the gear icon, it changes from half-strength to full white, but nothing happens. So the main charge bolt icon and the gear icon are both white, but I am still on the bolt icon tab. Longer press the gear does bring up the submenu, but that also brings up the "Open in new tab?" dialog in both browsers. 

Options for improvement:

a. Integrate all the blocks that are in the various submenu items into one longer scrolling page for "Settings", thereby removing this submenu entirely (this is my preference)
b. Make the menu popup on first short tap of the gear icon, and do not make it highlight white until one of the submenu items are tapped
c. If option b. is going to make the page too long, then if schedule block goes onto the bolt tab, there is room for a separate icon for "basic settings" and one for "advanced settings" next to each other.

Thoughts?

**Comment by KipK** [comment]
It was an unfinished wip, but I've removed the submenu.
