### ISSUE TITLE
If host unreachable, UI hangs at loading

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#16]
So my OpenEVSE is being really stubborn about connecting to my Wifi the past couple of days. Not reachable on the network.

I get console output in the terminal I launched nvm run dev from:

8:08:52 AM [vite] http proxy error at :
Error: connect EHOSTUNREACH ***LANIPHere***:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

But the UI just looks like it is stuck at 1/3 loaded. 

Could we add an error message about this if OpenEVSE cannot be contacted in ~30 seconds or so?

**Comment by KipK** [comment]
Yep it's undone yet. I'm out for 2 weeks for now ;)

**Comment by KipK** [comment]
I've fixed this for the initial fetchData. I'll have to do the same for the web socket
