### ISSUE TITLE
Demand Shaper not saving MQTT Topic "is Missing"

### ISSUE THREAD

**Issue by graememk** [KipK/openevse-gui-v2#20]
When I click Save on the Shaper setting, I get an error " Live Power mode MQTT is missing"

this setting has been carried over from the v1 
![image](https://user-images.githubusercontent.com/12351396/211054117-8b33c119-c824-4f03-b135-b19de861fb96.png)

![image](https://user-images.githubusercontent.com/12351396/211054146-bd31833f-d593-47ce-9791-d5e72ecb908b.png)
 
 Tried changing it, Still get the same error.

**Comment by KipK** [comment]
Thanks, it was a stupid typo I've introduced lately. Fixed now, binaries updated in RC3.
