### ISSUE TITLE
Bottom Nav Bar issue when running Chrome on Android 

### ISSUE THREAD

**Issue by aklnlh** [KipK/openevse-gui-v2#22]
Just giving this an initial test and when using the new interface using Chrome (v: 109.0.5414.86) on Android (v:11) the bottom of what looks to be all pages are covered up by the bottom navigation bar.  At this time I've not tested any other browsers or OS.  I will do some more testing and update as I go. 

Is there any further information that you need to assist in resolving this anomaly.

**Comment by KipK** [comment]
Can you post a screenshot here + resolution of your screen?

**Comment by aklnlh** [comment]
The Phone is an Oppo A9 2020
Screen resolution is 1600x720


![Screenshot_2023-01-14-14-35-26-01_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/44631439/212444664-9cb43fd0-30be-4c07-9e8a-53c4babba75f.jpg)

If I view as a desktop site, this is what I get. 

![Screenshot_2023-01-14-14-44-00-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/44631439/212445041-9cae3737-6992-4ae3-a82f-a196ceb21a86.jpg)

**Comment by aklnlh** [comment]
The Phone is an Oppo A9 2020
Screen resolution is 1600x720

![Screenshot_2023-01-14-14-35-26-01_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/44631439/212444918-a9736d67-9c84-4c42-8ea4-8e4038610a4c.jpg)

**Comment by KipK** [comment]
it's normal it's called responsive design :) layout change according to available space. 
The page scroll downs if there's not enough space , doesn't the page scroll down on your side?
I've removed the scroll inside the box and now extend the box itself as it's more ergonomic on little screen

**Comment by aklnlh** [comment]
I can slide the page down, but not enough to see the last two selections.  What you see in the screen shot is the page scrolled down as far as I can go, so I'm only able to view the top of the Developer box, but not the About box at all.

Once there is a new firmware to test, I'll install and test to let you know if you're changes have resolved this issue. Thanks

**Comment by KipK** [comment]
Thanks I have reprroduced your issue.

**Comment by KipK** [comment]
@aklnlh it's fixed now with many other things. You can grab new binaries
Have not finished yet to redo all the config forms. I have started to remove all unnecessary save button ( HTPP, MQTT for now )

**Comment by aklnlh** [comment]
I've updated and can confirm that the issue is no longer present. 
Thanks for your assistance.
