### ISSUE TITLE
Time limit expiration display

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#26]
Using nightly build from yesterday, after time limit expired, time remaining jumps up to 23:59:59, and charging enabled button remains green:

https://photos.app.goo.gl/KQWbXGcUuDWyoWcQ8

**Comment by KipK** [comment]
should be ok with latest commit.

**Comment by fhteagle** [comment]
Just loaded the nightly from about 9 hours ago. Now seeing time left is always 00:00:00, regardless of limit reached or not, charge enabled/disabled, override active or cleared, etc:

![Screenshot_20230217_081309](https://user-images.githubusercontent.com/9244278/219692767-fa6fc383-8e2d-416b-91a3-2a61f0aa4216.png)

**Comment by KipK** [comment]
Seems that's not the latest build or I haven't pushed the last fix then. On a plane for now will check later

**Comment by pdhoogh** [comment]
Yes, I see that too.
openevse_wifi_v1_openevse-gui-v2.bin downloaded 19 feb 2023.

**Comment by KipK** [comment]
Fixed  in main
