### ISSUE TITLE
Highlight disabled icon background on limit reached

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#28]
If no schedule is set, only "charge" and "disabled" icons are shown on main charging tab, which is expected. If a limit is later set and reached, neither "charge" nor "disabled" buttons are shown as selected / active (white background for either button).

If limit is reached, "disabled" button should have filled in red background.

**Comment by fhteagle** [comment]
Also, the robot head next to "Limit" in status block is not consistent with the rest of the GUI (i.e. robot head is for schedule). I suggest setting the icon in the status block line to correspond the kind of limit that was reached. If energy, display lightning bolt next to Limit, if time, use hourglass icon next to Limit.

**Comment by KipK** [comment]
Yep it's planned I've already selected the icons.
Also I have fixed the button states. It's now set to Off and buttons are disabled

**Comment by KipK** [comment]
should be ok with https://github.com/KipK/openevse-gui-v2/commit/80fc127fa1ffc67b5b148dd98e65164950fb7ff9
