### ISSUE TITLE
Current vs Power mismatch in Status Block

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#33]
Using Energy Meter + attempted schedule fix, and using Energy Meter only editions from Google Drive:

I found a case where disabling the OpenEVSE caused the displayed current to go to 0A as expected, but the Power block was stuck at the pre-disable value. This mismatched display continued after page refresh:

![Screenshot_20230306_174913](https://user-images.githubusercontent.com/9244278/223290762-93a85ec5-62f8-4536-8206-30405d3b1127.png)

**Comment by KipK** [comment]
Thanks I forgot to reset when not charging.  Fixed in EnergyMeter branch
