### ISSUE TITLE
Use of scheduling / timer seems to interact with charge modes 

### ISSUE THREAD

**Issue by pdhoogh** [KipK/openevse-gui-v2#35]
I've used the GUIv2 for a while now (4.1.8) and it works really well as long as you do not use scheduling.

Yesterday I used a combination of scheduling with an energy limit and FAST mode. The energy limit was the first hit. Later the one schedule entry to disable at a certain time kicked in. 

The next morning, I was not able to use the OpenEVSE in ECO mode because it was disabled. That is fine. But...

I removed the "disable" schedule and added a "enable" schedule to (to enable 2 minutes later). The OpenEVSE enabled, but ECO mode no longer worked. Even with the GUI set on ECO mode. It just gave max current. Resetting the WiFi did not work. When I removed all the timers ECO mode worked again.

**Comment by KipK** [comment]
This is a recent issue already known with scheduler  on wifi firmware: 

https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/560


Also already reported here https://github.com/KipK/openevse-gui-v2/issues/31
Should be fixed soon
