### ISSUE TITLE
Correctly display UI version? 

### ISSUE THREAD

**Issue by glynhudson** [KipK/openevse-gui-v2#36]
It's a minor issue, but I've noticed the UI version V1.0.0 is displayed. I think this should be V2.x.x when running the V2 UI to avoid any confusion with the V1 UI. 

![Screenshot from 2023-03-13 16-17-13](https://user-images.githubusercontent.com/758844/224763919-1236feb5-90f6-4062-b23d-0ec891d0800f.png)

**Comment by KipK** [comment]
yeah mostly because I've named it differently and it was the first version of this one. but I join you, will be less confusing to directly start by a v2.0.0

**Comment by KipK** [comment]
anyway I've removed the version number. It doesn't has much sense, it will be always delivered in bundle with the fw that is already versionned

**Comment by KipK** [comment]
it nows display like this

![image](https://user-images.githubusercontent.com/488789/224785924-188ce49f-3b45-4162-adad-de93c01a2b27.png)
