### ISSUE TITLE
Red colour should be reserved for error states

### ISSUE THREAD

**Issue by glynhudson** [KipK/openevse-gui-v2#37]
I've been in communication with @chris1howell and we both feel that red colour in the UI should be reserved for error states.

This is related to #13, I think the colours in the UI should match the colours on the RGB LCD where possible i.e sleeping / disabled is a purple colour. Although I'm not too fussed about the actual colour used, but I definitely think red should not be used unless there's an error. 

Currently, red is used in a number of places in the UI. I propose changing all instances of red to be purple, or dark blue to match other UI elements?

![Screenshot 2023-03-29 12 12 53](https://user-images.githubusercontent.com/758844/228519287-5888253f-8203-4f4c-9a57-c9b76469a00e.png)

**Comment by KipK** [comment]
Red is kind of of convention for stop/power off/disabling/Cancel...


Error state are also marked in red as they are supposed  to have switched the evse to a disabled state too. 

Using purple for such buttons, disabled status tags doesn't make much sense in a UX perspective.

What could be an other way?

**Comment by chris1howell** [comment]
There is a lot of information on the subject, especially if you look at
SCADA systems. This is a great resource linked below.

Alarm color should be bright and not used for anything else. Grey may be a
good choose for disable.

https://realpars.com/hmi-colors/

**Comment by KipK** [comment]
we are talking about UX conventions for main users not sure industrial conventions are really suited here.

But I get the point, will check how it goes with greyed out, but you loose a lot of emphasis

**Comment by KipK** [comment]
@chris1howell @glynhudson 
I've removed the red color for everything than errors. It's a bit less appealing but this will fit for now. 
I'll have to introduce a new color in the palette somewhere else, dunno yet.
It's pushed on master, new builds  are ok 

![image](https://user-images.githubusercontent.com/488789/228579742-dbfe6fa9-9e2a-4bfd-8b4f-2b3665773cf7.png)

**Comment by glynhudson** [comment]
Thanks, I've just flashed the new build. That's great, I like it. I think it looks more elegant, but importantly it will clearly highlight when there is an error. Having clear error reporting is very important for an EVSE.

**Comment by KipK** [comment]
I've added some visibility to errors, now monitoring nav button goes red if it gets error and default jump to Security tab : 

![image](https://user-images.githubusercontent.com/488789/228806471-8bbdb9c0-494b-4c86-952a-9dc328ae04ae.png)
