### ISSUE TITLE
Add the ability to set the time from the browser

### ISSUE THREAD

**Issue by jeremypoulter** [KipK/openevse-gui-v2#42]
The V2 GUI is missing the ability to set the time on the host browser. This is really handy should you be in a standalone setup with no internel access. Obviously you can use the manual time but this needs you to carefully set the correct time on the UI first, in the vast majority of cases the browser will have the correct time so it would be great to just use that. Probably should also set the timezone of the browser as well (that being said NTP should also default to the time zone of the browser if it doesn't get a sensible one from the EVSE).

**Comment by KipK** [comment]
when you set manual mode it automatically set to local browser time first. then you can change it if you want. 

I can force the tz to browser one if not set yet, for now it default to utc

**Comment by jeremypoulter** [comment]
This is likely to still be wrong though based on the time between switching to Manual mode and clicking on the button. In the v1 UI the time is read after clicking the button just before sending the request to the browser.

**Comment by KipK** [comment]
it set the time when you set to manual with the selector, there's no need on clicking on the set time button again.
Doesn't it works as it should ?

**Comment by KipK** [comment]
seems the get timezone from browser was not working as expected. I've fixed it on the shaper branch, will merge it later.

**Comment by KipK** [comment]
spotted something, when you're already in manual time mode, then the only way to update to browser time was switching back&forth from ntp. 

I've added a button also

![image](https://user-images.githubusercontent.com/488789/229373655-a0c144f1-ab53-4c3e-bb06-ce5313cf148a.png)

**Comment by jeremypoulter** [comment]
Ah I see, not too sure that will work, as if you consider the off line case. For example consider an OpenEVSE used as a portable charger that is taken on roadtrips so might need to set the time every stop, but you would only switch to manual when you first get the unit.

**Comment by KipK** [comment]
should work with the new button now.
Offline evse should definitevely have RTC, I can't imagine having to set the time each time you have to use it. :)
