### ISSUE TITLE
LED  brightness is optional 

### ISSUE THREAD

**Issue by jeremypoulter** [KipK/openevse-gui-v2#43]
LED support is only built in to some of the builds, if the firmware support is not enabled the option should not be enabled in the GUI. If the `led_brightness` property is not returned from `/config` then LED brightness control is not supported.

**Comment by KipK** [comment]
Thanks, fixed by https://github.com/KipK/openevse-gui-v2/commit/07816036e531e7613d39ad860f005e13af7caed2
