### ISSUE TITLE
Network shows as disconnected on Wired ethernet

### ISSUE THREAD

**Issue by jeremypoulter** [KipK/openevse-gui-v2#44]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/6116992/229315663-aae5935f-e2c4-4a74-ae04-90cfa4e09838.png">

**Comment by KipK** [comment]
for the connected status it use "net_connected" property, shoud i use another one  ?

**Comment by KipK** [comment]
it nows check booth wifi and eth connected status instead of net_connected.

**Comment by jeremypoulter** [comment]
Hum, that could be a bug in the firmware then `net_connected` should be either WiFi or Wired
