### ISSUE TITLE
Error state more prominent?

### ISSUE THREAD

**Issue by glynhudson** [KipK/openevse-gui-v2#45]
Currently, when the unit enters and error state on UI V2 it's quite subtle, and it's not possible to tell at a glance what the error is:

![Screenshot from 2023-04-04 15-03-18](https://user-images.githubusercontent.com/758844/229817871-2a4a63da-93af-407f-90a3-6888a4cbbe01.png)

Compared to normal charging:

![Screenshot from 2023-04-04 15-05-07](https://user-images.githubusercontent.com/758844/229818288-bddec3d0-fff0-4680-b6a1-fcfa8a1de127.png)

I think as a minimum the status border colour should glow red.

Personally I quite like the text on the old UI e.g Charging | Waiting | Vent error | GND fault etc. I understand if for UI aesthetics you prefer not to have text for 'Charging' or 'Waiting', however in the event of an error I would prefer the error message to be displayed clearly in text without having to mouseover or tap a logo.

**Comment by KipK** [comment]
the error are detailed in the tooltip of the error icon. Roll over, or tap the icon to display it.
You have more details of the errors then in Monitoring section.

What error was thatnot disabling the evse ? It should be in red if evse is  in error state

**Comment by glynhudson** [comment]
That was a diode error, I also tested with a vent error, both disabled the EVSE, but the background colour did not go red

**Comment by KipK** [comment]
![image](https://user-images.githubusercontent.com/488789/229985621-0ab78bd1-316d-4269-92a0-dfc5c1b169d7.png)
Doesn't seems to be disabled on your screen ( I have to check that)

**Comment by KipK** [comment]
Seems I have found why, fxed

**Comment by KipK** [comment]
I've added error message displayed in an alertbox and in monitoring/safety section.
