### ISSUE TITLE
LCD is corrupted during FW update 

### ISSUE THREAD

**Issue by glynhudson** [KipK/openevse-gui-v2#46]
I'm not sure what the correct repo is for this issue, I first noticed it after updating to UI V2. Let me know if you think I should move it to the main repo? 

https://user-images.githubusercontent.com/758844/229891054-cf603b66-ac28-4719-ae0d-67c11315be0e.mp4

**Comment by KipK** [comment]
I don't see the issue? it just looks to me that the lcd is lagging behind refresh updates

**Comment by glynhudson** [comment]
On the old FW the LCD would clear before the update started, so the only thing on display would be the percentage

**Comment by KipK** [comment]
Seems the fw doesn't clear the lcd for update from http. Should be in fw issue 

edit: strange, looking at lcd code now, it should display "Updating WiFi" on first line and the progrss on second, but should be clean.
There's a little bug somewhere

**Comment by KipK** [comment]
Probably came with update from HTTP changes. Needs to be posted on firmware issues.  Should ask Jeremy he knows better this part of code.
