### ISSUE TITLE
FW upload success message

### ISSUE THREAD

**Issue by glynhudson** [KipK/openevse-gui-v2#47]
When FW upload completers on UI V2 there does not seem to be any success message, it would be a good idea to add a message like this if FW upload is successful:

![Screenshot from 2023-04-05 00-31-47](https://user-images.githubusercontent.com/758844/229944766-fc5239f9-8492-40e1-8ca2-8cdc0dd76129.png)

**Comment by KipK** [comment]
ah thabnks, it was supposed to display a message, was truncated by another condition. Fixed
