### ISSUE TITLE
Elapsed time continues to run with OpenEVSE disabled

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#48]
I think I remember that the elapsed time counter would stop when the OpenEVSE was in Manual Override: On, status: disabled. But with 4.1.9 firmware, the counter seems to keep running anyway. Bug or by design?

Possibly related to https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/594

Testing master_2e570854 to see if its still present...

**Comment by KipK** [comment]
I've fixed a missing case, thanks
