### ISSUE TITLE
where is the Interface language selection menu?

### ISSUE THREAD

**Issue by zerodur12** [KipK/openevse-gui-v2#49]
I haven't been able to find in the new interface a menu where you can select the langage for the interface from en, es and fr?
This selection was possible in the previous interface.

**Comment by jeremypoulter** [comment]
It is under the HTTP page in settings:
![Screenshot_20231126-094640.png](https://github.com/KipK/openevse-gui-v2/assets/6116992/cc9f840d-2546-4f19-80a2-ef5d5d1e35cf)

**Comment by jeremypoulter** [comment]
It is under the HTTP page in settings:
![Screenshot_20231126-094640.png](https://github.com/KipK/openevse-gui-v2/assets/6116992/cc9f840d-2546-4f19-80a2-ef5d5d1e35cf)

**Comment by zerodur12** [comment]
Thanks
