### ISSUE TITLE
Status icons suggestions

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#5]
I am confused by the Charging status icon div using the class "is-warning" / yellow color? I would think this would be a normal condition, and green in color instead?

![Screenshot_20221111-110153](https://user-images.githubusercontent.com/9244278/201403506-ae4ca358-950a-4f06-bb05-b76b06f00f1a.jpg)

The waiting to charge icon is a green background checkered flag:

![Screenshot_20221111-110004](https://user-images.githubusercontent.com/9244278/201403338-7e9bdd62-b7dc-47a2-9b83-91d3728c7a73.jpg)

This, to me, means "completed". Change it to a blue background hourglass icon, or maybe a clock icon?

<s> Status icon label "Sleeping" does not have much meaning to me. What is this status communicating? It seems to me to be redundant with the red paused icon? </s>

**Comment by KipK** [comment]
I don't get it. First icon represent the Openevse state ( active / disabled ) 
The waiting Icons replace the Sleep Icon when state is active and no vehicule is plugued 

Sleep is same state as displayed on LCD , when it's disabled and nothing connected.

![icons](https://user-images.githubusercontent.com/488789/201332245-7e3228c7-0648-423d-bb92-f0327374e589.png)

**Comment by fhteagle** [comment]
If the OpenEVSE is active, the EV is connected, but EV is not actually charging (due to EV internal charging time configuration), the third icon is a checkered flag with green background. I will get my system into this state and take a screen shot later today.

**Comment by KipK** [comment]
Ah I see, . I've changed for thumbs-up , let's see if it's more appropriated if you have other suggestions

**Comment by fhteagle** [comment]
I updated the original post with screenshots for clarity about what I was talking about.

I think you changed the blue moon with tooltip "Sleeping" to be the blue thumbs up, correct? This is not what I was trying to indicate. Probably my mistake for not being clear enough.

What if the green background flag was changed to a blue background hourglass, and make the tooltip say, "EV not yet charging"?

**Comment by KipK** [comment]
oups nope I've made a mistake, now it(s the good ones

**Comment by fhteagle** [comment]
Okay, the last icon being thumbs up and tooltip "Ready to Charge" for when the EV is not yet drawing power makes sense to me now. Thanks for fixing it!

Back to the charging icon being a yellow is-warning... I still think this should be green background for a normal condition.

**Comment by KipK** [comment]
The idea here is to give emphasis to state "Charging" by introducing a unique color. 

Choosed Yellow as it fits for a lighning icon ( perhaps using a lightning Icon is more suited in this case. 

Perhaps using Blue then ?

**Comment by KipK** [comment]
I've changed for Bolt icon, green background, and yellow icon color.
Does this makes more sense ?  ( Bolt icon is also more readable on little screen )

**Comment by fhteagle** [comment]
Yellow bolt on green background makes visual and logical sense to me. Good compromise between "this is normal" and "careful, power is flowing". 

I wonder if a color blind person could see the yellow on green, though. I have a partial color shift, but not full color blindness. The white on green, or white on blue, or white on red each should have enough contrast to be legible. Yellow on green might be too close in contrast.

**Comment by fhteagle** [comment]
Since you are using the "Pause" icon for OpenEVSE disabled in the status box, what about using that for Mode: OFF , instead of the circle and slash? 

Same suggestion about harmonizing Mode: ON icon and enabled status icon?

**Comment by KipK** [comment]
I was about to change the pause icon too, testing live some different ones. Seems the circle & slash is more appropriated to a disabled state. 
Or perhaps we can change this icon depending we have an auto_release true or not . Pause Icon could be appripriated for an auto release true, the other one when false

I won't use the bolt icon too for this as it will be confusing with the Charging state. I'm still not fan of the Circle Check we have now either :)
Or pehaps we use bolt for Charge button and Active status,, we remove the Charging status Icon, and just use the bolt in yellow while charging in the current state icon


New thing I've just added, tell me what do you think about this:
https://watch.screencastify.com/v/rfUevvOop9RcR79mJ7ud

It displays the current service that has the claim on the max_current setting here ( but could work like this for any property ) 
You can them from here delete any claim made by a service with lower priority than manual

**Comment by KipK** [comment]
ok I'm testing this, not bad, and less Icon on screen for same message:
dizsabled:
![image](https://user-images.githubusercontent.com/488789/202773376-0334311c-18a7-42c5-a8b1-ec446e3a20cb.png)
active, waiting for EV
![image](https://user-images.githubusercontent.com/488789/202773247-f90e9c4a-049e-4205-9aa6-1cd3df02a341.png)
active, EV connected: 
![image](https://user-images.githubusercontent.com/488789/202773693-949e0b1e-59da-4a50-926c-f0ed443c6d57.png)
active: charging:
charging:
![image](https://user-images.githubusercontent.com/488789/202773862-1c4a2ac5-ef8d-4f53-b4ab-0034b99ab4b5.png)
error:
![image](https://user-images.githubusercontent.com/488789/202773969-00b0fe1c-c0b6-4f45-92a2-5fc155de659c.png)

Then we have a bit more space on mobile to display a message

**Comment by fhteagle** [comment]
Two icons is still very clear and yes a bit more simple!

As to the Screencast with the MQTT thing ... I had written up an idea to display the various amp setpoints from Eco, MQTT, etc, each on their own line. Even if the automated amp levels cannot be changed by user in GUI, having multiple slider bars the same size that moved in response to what that automated control was commanding right now would be easy to compare visually. I.e., user asks self why am I only charging at 10 amps now, looks at sliders, sees lowest is shaper, oh that's why....

 I think this might be better than trying to reuse one slider + manual/MQTT toggle.

**Comment by KipK** [comment]
that's what is happening here. The slider will adjust the value to related claim that has the priority , and display the claim id as a tag under the slider. :)

There's no need to display the whole /claims topic for all the other claims that are not taken in consideration yet. The live one should be sufficient. 
I haven't done it yet, but the delete button will appear only to service with lower or equal priority as override, and also not for divert

I have iconified few things 
![image](https://user-images.githubusercontent.com/488789/202825459-dc51c975-42a3-46dd-a2ec-2c0aaf02b3bf.png)

**Comment by fhteagle** [comment]
Hmm. I have a different opinion on this. I think it would be useful to be able to see the action of each "amp controller",  and be able to easily toggle each on and off from the main page. Seeing a unified table of all the configured "controllers" is a great overview. And being able to see what would be happening with a particular controller, even if not active, would help the user to learn the system, confirm the system is configured as expected, and to notice unwanted quirks in what a controller is asking for. 

But I will admit that my opinion is not so well informed, as I have yet to configure any amp controllers on my home setup just yet.

**Comment by KipK** [comment]
Imagine how bloated it would be as each property can have a different controller, so tracking the list off all the claims that are ignored for now.

Anyway, evse has no idea on who will have the priority but the main one.  Those fuzzy logic would have to run on client side.
Also those claims are always moving in real time,  priority change etc, .

The only thing we can display without ending with a blinking data christmas tree is the main order for each property.
