### ISSUE TITLE
With Charge ON, mask Next Event

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#7]
If Charge ON is selected (aka manual_override: 1), Current Event and Next Event trigger times are ignored (as they should be). This should be communicated to the user somehow visually. Some options:

- Hiding these altogether
- Greying these out
- Strikethrough?

**Comment by KipK** [comment]
I've adressed this by displaying manual mode instead

**Comment by fhteagle** [comment]
Confirmed working as expected in commit 42a7e57cbb1302f02347b5a306818435302f45b8, thank you!
