### ISSUE TITLE
Status block sometimes stops updating

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#8]
I discovered a case where the status block stops updating. I do not have a way to solidly reproduce just yet, but I will keep trying. Might be just an in progress dev bug. Opening this just to remind myself to test more later.

Screenshot showing status bar has not updated in over 4 minutes:

![Screenshot_20221111_113124](https://user-images.githubusercontent.com/9244278/201408077-82a3e033-8151-4a01-9233-0bd95aed930b.png)

**Comment by KipK** [comment]
try to catch what logs has thrown, like web socket disconnection / error
Also go in Developper window / Network / get the /ws request, and check the message tab.
You'll see there if the websocket is still receiving data. If not I'd like to know why, as there's some reconenction logic in place.

**Comment by fhteagle** [comment]
Found this warning in browser dev console, don't remember seeing it before:

![Screenshot_20221112_081251](https://user-images.githubusercontent.com/9244278/201480738-be48053c-2979-4ff6-afeb-0ddee7fe63b0.png)

All of the endpoints load in other browser tabs. There is a openevse-gui-v2/dev-dist/registerSW.js , but not in /dev folder. Should I be running ```npm run build``` before ```npm run dev``` ?

**Comment by KipK** [comment]
those are not related. There will be a lot of warning and stuff as it's a dev in progress. Don't bother on them.

the registerSW.js missing is normal it's for progressive webapps 

however some stuff won't works as expected from now, as it needs changes on the evse firmware that are not merged yet.

**Comment by KipK** [comment]
this should be fixed now. Reopen if not.

**Comment by fhteagle** [comment]
Test commit 15c159c2276e0fe5a7e747af1c21efd02d8cf118   against 7.1.3 / 4.1.5 physical OpenEVSE, but I am not seeing the clock in the upper right advancing to keep up with the current time. I assume this means status block is not updating. Is this because I am not running your dev branch firmware?

**Comment by fhteagle** [comment]
Also, I appear to not have the privileges necessary to re-open this issue.

**Comment by KipK** [comment]
The clock thing was a wip I have forgottent to finish :) Thanks 

It should be good, I don't think  you need the new build for that.

**Comment by fhteagle** [comment]
At commit c7b3078fb93058547da433a6d3b6646a54ecd3f4

So the current time clock in the upper right advanced for about a minute, then froze again. Tried again and got the same results 3 different times in 3 different browsers.

Changed to Mode: ON in one browser, but the mode change did not get reflected on a different browser on my mobile device (still had the robot head timer lines, not the manual line). 

Amps, Power, Delivered, etc. seem to update as expected. Elapsed seems stuck though.

**Comment by KipK** [comment]
should be ok, please ask for reopen if not.
